[logging]
level = "debug,sqlx=debug"
format = "text"

[postgres]
timeout = 30               # seconds
max_connections = 20
min_connections = 5
max_lifetime = 1800        # 30 minutes
idle_timeout = 600         # 10 minutes

